services:
  server:
    container_name: ${APP_NAME}
    build:
      context: .
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html/WebRoot:rw

  mysql:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_DATABASE: 'finance_app'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
